import { PartialType } from '@nestjs/swagger';

import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2025-12-05T03:42:37.204Z
// ****************************** Base Resume response dto ******************************
export class BaseResumeResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  userId: number;

  @PropertyDto()
  avatar: string;

  @PropertyDto()
  name: string;

  @PropertyDto()
  dateOfBirth: string;

  @PropertyDto()
  gender: string;

  @PropertyDto()
  email: string;

  @PropertyDto()
  phoneNumber: string;

  @PropertyDto()
  address: string;

  @PropertyDto()
  profession: string;

  @PropertyDto()
  language: string;

  @PropertyDto()
  website: string[];

  @PropertyDto()
  professional: string;

  @PropertyDto()
  summary: string;

  @PropertyDto()
  skills: string[];

  @PropertyDto()
  isPublic: boolean;

  @PropertyDto()
  createdAt: Date;

}

// ****************************** GET Resume dto ******************************
export class GetResumeDetailResponseDto extends BaseResumeResponseDto {
  // Add more fields if needed such as relations
}

export class GetResumeListResponseDto extends BaseResumeResponseDto {
  // Add more fields if needed such as relations
}

export class GetResumeListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  userId: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  avatar: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  name: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  dateOfBirth: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  gender: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  profession: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  language: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  website: string[];

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  professional: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  summary: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  skills: string[];

  @PropertyDto({
    type: Boolean,
    required: false,
    validated: true,
  })
  isPublic: boolean;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;


  @MultipleOrderBy(DatabaseModelFields.Resume)
  orderBy: string[];
  
}

// ****************************** CREATE Resume dto ******************************
// todo: delete this line if you have corrected the dto
export class CreateResumeBodyDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  userId: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  avatar: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  name: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  dateOfBirth: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  gender: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  profession: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  language: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  website: string[];

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  professional: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  summary: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  skills: string[];

  @PropertyDto({
    type: Boolean,
    required: true,
    validated: true,
  })
  isPublic: boolean;

}

export class CreateResumeResponseDto extends BaseResumeResponseDto {}

// ****************************** UPDATE Resume dto ******************************
// todo: delete this line if you have corrected the dto
export class UpdateResumeBodyDto extends PartialType(CreateResumeBodyDto) {
  // User OmitType if needed
}

export class UpdateResumeResponseDto extends BaseResumeResponseDto {}

// ****************************** More Resume dto below ******************************
