import { PartialType } from '@nestjs/swagger';
import { Gender } from '@prisma/client';
import { JsonValue } from '@prisma/client/runtime/library';

import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { IsEmail, IsUrl } from 'class-validator';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// ****************************** additional ******************************
export class ExperienceDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  companyName: string

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  jobTitle: string

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  startDate: Date

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  endDate: Date

  @PropertyDto({
    type: Boolean,
    required: false,
    validated: true,
  })
  isCurrent: boolean

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  jobDescription: string
}


export class EducationDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  institutionName: string

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  degree: string

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  fieldOfStudy: string

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  graduationDate: Date

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  gpa: string
}

export class ProjectDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  projectName: string
  
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description: string
  
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    structure: 'array',
  })
  technologies: string[] & JsonValue[]
}

export class CertificationDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  name: string
  
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  issuer?: string
  
  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  issueDate?: Date
  
  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  expiryDate?: Date
  
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  credentialId?: string
  
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  credentialUrl?: string
}


// Auto generated by tools/generate-dtos.ts at 2025-12-08T14:29:38.064Z
// ****************************** Base Resume response dto ******************************
export class BaseResumeResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  userId: number;

  @PropertyDto()
  title: string;

  @PropertyDto()
  avatar: string;

  @PropertyDto()
  name: string;

  @PropertyDto()
  dateOfBirth: Date;

  @PropertyDto({
    type: Gender,
    structure: 'enum'
  })
  gender: Gender;

  @PropertyDto()
  email: string;

  @PropertyDto()
  phoneNumber: string;

  @PropertyDto()
  address: string;

  @PropertyDto()
  profession: string;

  @PropertyDto()
  language: string;

  @PropertyDto()
  website: string[];

  @PropertyDto()
  professional: string;

  @PropertyDto()
  summary: string;

  @PropertyDto()
  skills: string[];

  @PropertyDto()
  experiences: any;

  @PropertyDto()
  educations: any;

  @PropertyDto()
  projects: any;

  @PropertyDto()
  certifications: any;

  @PropertyDto()
  template: string;

  @PropertyDto()
  accentColor: string;

  @PropertyDto()
  fontFamily: string;

  @PropertyDto()
  isPublic: boolean;

  @PropertyDto()
  createdAt: Date;

}

// ****************************** GET Resume dto ******************************
export class GetResumeDetailResponseDto extends BaseResumeResponseDto {
  // Add more fields if needed such as relations
}

export class GetResumeListResponseDto extends BaseResumeResponseDto {
  // Add more fields if needed such as relations
}

export class GetResumeListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  userId: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  avatar: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  name: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  dateOfBirth: Date;

  @PropertyDto({
    type: Gender,
    required: false,
    validated: true,
    structure: 'enum'
  })
  gender: Gender;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  profession: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  language: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  website: string[];

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  professional: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  summary: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  skills: string[];

  @PropertyDto({
    type: Boolean,
    required: false,
    validated: true,
  })
  isPublic: boolean;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;


  @MultipleOrderBy(DatabaseModelFields.Resume)
  orderBy: string[];

}

// ****************************** CREATE Resume dto ******************************


export class CreateResumeBodyDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: 'My Awesome CV',
  })
  title: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: `https://upload.wikimedia.org/wikipedia/en/5/5f/Original_Doge_meme.jpg`
  })
  @IsUrl({
    require_tld: false,
    require_protocol: true,
  })
  avatar: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: `Uyn Nhi`
  })
  name: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  dateOfBirth: Date;

  @PropertyDto({
    type: Gender,
    required: false,
    validated: true,
    structure: 'enum'
  })
  gender: Gender;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: `nhinhi07@gmail.com`
  })
  @IsEmail()
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  profession: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  language: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: 'https://example.com'
  })
  @IsUrl({
    require_tld: false, // allow localhost / internal domains
    require_protocol: true,
  })
  website: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  professional: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  summary: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    structure: 'array'
  })
  skills: string[];

  @PropertyDto({
    type: ExperienceDto,
    required: false,
    validated: true,
    structure: 'dtoArray'
  })
  experiences: ExperienceDto[] & JsonValue[];

  @PropertyDto({
    type: EducationDto,
    required: false,
    validated: true,
    structure: 'dtoArray'
  })
  educations: EducationDto[] & JsonValue[];

  @PropertyDto({
    type: ProjectDto,
    required: false,
    validated: true,
    structure: 'dtoArray'
  })
  projects: ProjectDto[] & JsonValue[];

  @PropertyDto({
    type: CertificationDto,
    required: false,
    validated: true,
    structure: 'dtoArray'
  })
  certifications: CertificationDto[] & JsonValue[];

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: 'classic',
  })
  template: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: '#3B82F6',
  })
  accentColor: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    example: 'inter',
  })
  fontFamily: string;

  @PropertyDto({
    type: Boolean,
    required: false,
    validated: true,
  })
  isPublic: boolean;
}

export class CreateResumeResponseDto extends BaseResumeResponseDto { }

// ****************************** UPDATE Resume dto ******************************
// todo: delete this line if you have corrected the dto
export class UpdateResumeBodyDto extends PartialType(CreateResumeBodyDto) {
  // User OmitType if needed
}

export class UpdateResumeResponseDto extends BaseResumeResponseDto { }

// ****************************** Resume Score DTOs ******************************

export class CreateResumeScoreBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  resumeId: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  score: number;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  jdText: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  matchedRole?: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  missingSkills: string[];

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  weakSections: string[];

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  suggestions: string[];
}

export class ResumeScoreResponseDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  resumeId: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  userId?: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  score: number;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  jdText: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  matchedRole?: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  missingSkills: string[];

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  weakSections: string[];

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    structure: 'array',
  })
  suggestions: string[];

  @PropertyDto({
    type: Date,
    required: true,
    validated: true,
  })
  createdAt: Date;

  @PropertyDto({
    type: Date,
    required: true,
    validated: true,
  })
  updatedAt: Date;
}

export class GetResumeScoreListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  resumeId: number;
}

// ****************************** More Resume dto below ******************************
